version: '3.8'

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile-prod
      args:
        NODE_ENV: ${NODE_ENV}
        DB_PORT: ${POSTGRES_DB_PORT}
        DB_HOST: ${POSTGRES_DB_HOST}
    environment:
      - NODE_ENV=${NODE_ENV}
      - DB_PORT=${POSTGRES_DB_PORT}
      - DB_HOST=${POSTGRES_DB_HOST}
    depends_on:
      - db-prod
    volumes:
      - app-logs:/var/log/brewly-backend

  db-prod:
    image: postgres:13
    container_name: db-prod
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "${SERVER_PGADMIN_PORT}:${PGADMIN_PORT}"
    depends_on:
      - db-prod

  loki:
    image: grafana/loki:2.7.3
    container_name: loki
    command: -config.file=/etc/loki/loki-config.yaml
    volumes:
      - ./loki-config.yaml:/etc/loki/loki-config.yaml:ro
      - loki-data:/loki
    restart: unless-stopped

  promtail:
    image: grafana/promtail:2.7.3
    container_name: promtail
    restart: unless-stopped
    volumes:
      - app-logs:/var/log/brewly-backend:ro
      - ./promtail-config.yaml:/etc/promtail/promtail-config.yaml:ro
      - promtail-positions:/tmp
    command: -config.file=/etc/promtail/promtail-config.yaml

  grafana:
    image: grafana/grafana:9.2.0
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: brewly-backend-nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certbot/www:/var/www/certbot:rw
      - ./certbot/conf:/etc/letsencrypt:rw
    depends_on:
      - app

volumes:
  db-prod:
  app-logs:
  promtail-positions:
  grafana-data:
  loki-data: