export const ErrorSubCode = {
  USER_NOT_VERIFIED: 'USER_NOT_VERIFIED',
  USER_ALREADY_EXIST: 'USER_ALREADY_EXIST',
  USER_DOESNT_EXIST: 'USER_DOESNT_EXIST',
  INCORRECT_PASSWORD: 'INCORRECT_PASSWORD',
  INCORRECT_EMAIL: 'INCORRECT_EMAIL',
  INCORRECT_OTP: 'INCORRECT_OTP',
  CANT_DELIVER_VERIFICATION_EMAIL: 'CANT_DELIVER_VERIFICATION_EMAIL',
  COMPANY_NOT_FOUND: 'COMPANY_NOT_FOUND',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  REQUEST_VALIDATION_ERROR: 'REQUEST_VALIDATION_ERROR'
} as const;

export type ErrorSubCodeType = typeof ErrorSubCode[keyof typeof ErrorSubCode];