---
- name: Install & configure Nginx + SSL
  hosts: backend_servers
  become: true

  # If you’re using group_vars/all.yml, no need for vars_files

  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: true

  tasks:
    - name: Ensure nginx & certbot packages are installed
      apt:
        name:
          - nginx
          - certbot
          - python3-certbot-nginx
        state: latest

    - name: Render main nginx.conf
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify: Reload nginx

    - name: Render site conf into sites-available
      template:
        src: default.conf.j2
        dest: /etc/nginx/sites-available/{{ domain }}.conf
        owner: root
        group: root
        mode: '0644'
      notify: Reload nginx

    - name: Enable site by symlinking to sites-enabled
      file:
        src: /etc/nginx/sites-available/{{ domain }}.conf
        dest: /etc/nginx/sites-enabled/{{ domain }}.conf
        state: link
      notify: Reload nginx

    - name: Check for existing Let's Encrypt certificate
      stat:
        path: /etc/letsencrypt/live/{{ domain }}/fullchain.pem
      register: cert

    - name: Obtain Let's Encrypt certificate
      command: >
        certbot --nginx
        --non-interactive
        --agree-tos
        --email {{ email }}
        -d {{ domain }}
      when: not cert.stat.exists
      notify: Reload nginx

  handlers:
    - name: Reload nginx
      service:
        name: nginx
        state: reloaded