name: Deploy to VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Pull & Restart on VPS
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            cd /root/brewly-backend

            # ensure origin is SSH
            git remote set-url origin git@github.com:${{ github.repository }}.git

            # fetch & reset to master
            git fetch --all
            git reset --hard origin/master

            # use the newer Docker CLI plugin to avoid distutils errors
            docker compose -f docker-compose-prod.yaml --env-file ${{ secrets.ENV_FILE_PATH }} up --build -d
          EOF