name: Deploy to VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH key for VPS
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Pull & Deploy on VPS
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            set -eux

            # Ensure Docker Compose plugin is installed (for `docker compose`)
            if ! docker compose version >/dev/null 2>&1; then
              apt-get update
              apt-get install -y docker-compose-plugin
            fi

            # Navigate to your application directory
            cd /root/brewly-backend

            # Trust GitHub's host key to avoid verification failures
            mkdir -p ~/.ssh
            ssh-keyscan github.com >> ~/.ssh/known_hosts

            # Use the SSH URL for pulling code
            git remote set-url origin git@github.com:Drogonov/brewly-backend.git

            # Fetch the latest commits and reset
            git fetch --all
            git reset --hard origin/master

            # Deploy with Docker Compose plugin
            docker compose \
              -f docker-compose-prod.yaml \
              --env-file config/production.env \
              up --build -d
          EOF
