name: Deploy to VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      GH_PAT: ${{ secrets.GH_PAT }}        # 1️⃣ expose your PAT to the step

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH key for VPS
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Pull & Deploy on VPS
        run: |
          ssh -o StrictHostKeyChecking=no \
              ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << EOF   # ← no quotes around EOF
            set -eux

            cd /root/brewly-backend

            # trust GitHub host key
            mkdir -p ~/.ssh
            ssh-keyscan github.com >> ~/.ssh/known_hosts

            # 2️⃣ switch remote to HTTPS+token
            git remote set-url origin \
              https://$GH_PAT@github.com/Drogonov/brewly-backend.git

            # fetch and reset
            git fetch --all
            git reset --hard origin/master

            # 3️⃣ deploy with docker compose
            docker compose \
              -f docker-compose-prod.yaml \
              --env-file /root/brewly-backend/config/production.env \
              up --build -d
          EOF